Class {
	#name : 'ChrysalConvertedCompositeDomain',
	#superclass : 'Object',
	#instVars : [
		'newLine',
		'htmlTemplate',
		'title'
	],
	#category : 'Chrysal-Tests-Mocks',
	#package : 'Chrysal-Tests',
	#tag : 'Mocks'
}

{ #category : 'accessing' }
ChrysalConvertedCompositeDomain >> htmlTemplate [
	^ htmlTemplate
]

{ #category : 'accessing' }
ChrysalConvertedCompositeDomain >> htmlTemplate: anObject [
	htmlTemplate := anObject
]

{ #category : 'accessing' }
ChrysalConvertedCompositeDomain >> newLine [
	^ newLine
]

{ #category : 'accessing' }
ChrysalConvertedCompositeDomain >> newLine: anObject [
	newLine := anObject
]

{ #category : 'accessing' }
ChrysalConvertedCompositeDomain >> title [
	^ title
]

{ #category : 'accessing' }
ChrysalConvertedCompositeDomain >> title: anObject [
	title := anObject
]
