"
Chrysal is composed in two parts:
- a configuration description and builder
- a runtime part (a generated configuration reader)

This package is about the first part. It lets the user declare a configuration and the builder will generate a new class that is able to read and validate configurations.
"
Class {
	#name : 'ManifestChrysal',
	#superclass : 'PackageManifest',
	#category : 'Chrysal-Manifest',
	#package : 'Chrysal',
	#tag : 'Manifest'
}
